### PR TITLE
More informative error message in `update_ensemble!`

### LINKED ISSUE #76: Slightly clearer error message for incorrect ensemble sizes
Perhaps instead of

https://github.com/CliMA/EnsembleKalmanProcesses.jl/blob/da4b7da856622b1b1963c0f6193f1022dd237d66/src/EnsembleKalmanInversion.jl#L60-L62

something like

"`N_ens` in EnsembleKalmanProcess and g do not match..."

or "Ensemble size `N_ens` in EnsembleKalmanProcess..."

The first time I saw this error, it took me a little while to figure out that `N_ens` _is_ the ensemble size.

### PR DESCRIPTION
**Pull request by navidcy**
Closes #76

### CODE REVIEW

File: src/EnsembleKalmanInversion.jl [hunk 1]
```diff
@@ -58,7 +58,7 @@ function update_ensemble!(
 
     #catch works when g non-square
     if !(size(g)[2] == ekp.N_ens)
-        throw(DimensionMismatch("ensemble size in EnsembleKalmanProcess and g do not match, try transposing g or check ensemble size"))
+        throw(DimensionMismatch("ensemble size `N_ens` in EnsembleKalmanProcess does not match the columns of `g`; try transposing `g` or check the ensemble size"))
```
Comment (ilopezgp) [inline src/EnsembleKalmanInversion.jl:61]: throw(DimensionMismatch("ensemble size N_ens=$(ekp.N_ens) in EnsembleKalmanProcess does not match the columns of g ($(size(g)[2])); try transposing g or check the ensemble size"))

Comment (ilopezgp) [inline src/EnsembleKalmanInversion.jl:61]:
```suggestion
        throw(DimensionMismatch("ensemble size $(ekp.N_ens) in EnsembleKalmanProcess does not match the columns of g ($(size(g)[2])); try transposing g or check the ensemble size"))
```

**Review by ilopezgp — APPROVED** [review]
