### PR TITLE
Fix bug with kwargs not being passed for plotting

### LINKED ISSUE #556: Keyword arguments not being passed properly for visualization
Between EnsembleKalmanProcesses v2.6.0 and v2.6.1, the keyword arguments are not being passed properly to Makie. This can be seen by inspecting the docs for the visualization section of the docs.

See the visualization section for 2.6.1: https://clima.github.io/EnsembleKalmanProcesses.jl/v2.6.1/visualization/
and the visualization section for 2.6.0: https://clima.github.io/EnsembleKalmanProcesses.jl/v2.6.0/visualization/

I am guessing that the update to make the plotting compatible with Makie v0.24 is the reason behind this.

### PR DESCRIPTION
**Pull request by ph-kev**
closes https://github.com/CliMA/EnsembleKalmanProcesses.jl/issues/556

This PR updates how `@recipe` was called and how the attributes are accessed to pass the keyword arguments to Makie plotting functions. This PR also clean up the unused `auto_log_scale` keyword argument which isn't implemented.

### CODE REVIEW

File: ext/EnsembleKalmanProcessesMakieExt.jl [hunk 1]
```diff
@@ -230,15 +235,16 @@ function Makie.plot!(plot::ErrorAndItersOrTime)
     xvals = plot.xvals[]
     errors = get_error_metrics(plot.ekp[])[plot.error_metric[]]
     valid_attributes = Makie.shared_attributes(plot, Makie.Lines)
```
Comment (imreddyTeja) [inline ext/EnsembleKalmanProcessesMakieExt.jl]:
```suggestion
```

File: ext/EnsembleKalmanProcessesMakieExt.jl [hunk 2]
```diff
@@ -138,7 +141,9 @@ Any keyword arguments is passed to the plotting function which takes in any
 keyword arguments supported by
 [`Makie.Lines`](https://docs.makie.org/dev/reference/plots/lines).
 """
-Visualize.plot_error_over_iters(args...; kwargs...) = _plot_error_over_iters(erroranditersortime, args...; kwargs...)
+function Visualize.plot_error_over_iters(args...; kwargs...)
```
Comment (imreddyTeja) [inline ext/EnsembleKalmanProcessesMakieExt.jl]: was this just a formatting change?

File: docs/src/visualization.md [hunk 3]
```diff
@@ -184,7 +184,7 @@ viz.plot_ϕ_over_time(
     ekp,
     prior,
     "two_with_spread_2",
-    linewidth = 1.5)
+    markersize = 8)
```
Comment (imreddyTeja) [inline docs/src/visualization.md:187]: Is this something that should have been updated previously?

Comment (ph-kev) [reply docs/src/visualization.md:187]: Yes, since `linewidth` didn't do anything.

File: ext/EnsembleKalmanProcessesMakieExt.jl (hunk 2 above)
Comment (ph-kev) [reply ext/EnsembleKalmanProcessesMakieExt.jl]: Oops. I forgot to undo this.

**Comment by imreddyTeja** [comment]
Why is there no documentation/docs-deploy in this repo?

**Review by imreddyTeja — APPROVED** [review]

**Comment by odunbar** [comment]
Docs page here: @imreddyTeja 
https://clima.github.io/EnsembleKalmanProcesses.jl/previews/PR558/visualization/

We did used to have it come up below in the GitHub checks, but unsure when it stopped doing this haha

**Review by odunbar — APPROVED** [review]
